### ISSUE TITLE
need help on mysql issue

### ISSUE THREAD

**Issue by sittikhadijah** [mushorg/glastopf#111]
Hello i'm newbie in glastopf, would you like to help me ?? i want to store attack information in a MySQL database. but i dont know the configuration steps. my problem is i dont know how to add mysql.py in the glastopf.cfg plug-in section 7.2.2.2 and add the MySQL connection information in the MySQL section 7.2.2.3. i also can't find structures folder in the
Glastopf directory. I really need your help. Thanks before.

**Comment by akanshgulati** [comment]
Can anyone share the syntax for connection mysql instead of sqlite.
I have a database with the name glastopf, user is root and host is localhost. Where I have to add the password of the root?

**Comment by glaslos** [comment]
`mysql://root:password@localhost/glastopf`
