### ISSUE TITLE
glastopf sql injection emulation

### ISSUE THREAD

**Issue by sittikhadijah** [mushorg/glastopf#115]
i already installed glastopf as my honeypot, then i wanna test it. what should i prepare if i want to emulate sql injection in glastopf?? this is the screenshot of my web browser when i access localhost : https://f.cloud.github.com/assets/4487074/589777/3e2e71d0-c9cb-11e2-8d3e-443d4321f57f.png

**Comment by hawana8822** [comment]
@sittikhadijah hi , i want to know how you emulate sql injection in glastopf??
