### ISSUE TITLE
Test TAXII/STIX implementation with MANTIS

### ISSUE THREAD

**Issue by johnnykv** [mushorg/glastopf#159]
We should test our integration with [MANTIS](http://django-mantis.readthedocs.org/), We can do this when they have the TAXII (django-mantis-taxii) endpoint ready.
This realtes to #77

**Comment by jai6684** [comment]
Hi have you the integration with Mantis.?

I want to ass the Threat Intelligence data into QRadar can ou help me please.

**Comment by glaslos** [comment]
I am not aware that someone tested importing the STIX reports from Conpot into MANTIS.
