### ISSUE TITLE
Sitemap generation based on dorks

### ISSUE THREAD

**Issue by 5pld3y** [mushorg/glastopf#187]
I have been thinking about getting more hits on the POT.  However, getting traffic from search engine can become faster if we submit sitemaps as per the dorks. 

However, I am not clear how the dorks are being handled presently.

**Comment by glaslos** [comment]
we have one page with bogus links to other pages. Those other pages are basically the same page with other dorks. It's an endless mace. Every x minutes we create a set of 50 pages. In that step you would need to create the sitemap. Have a look at the code here: https://github.com/glastopf/glastopf/blob/master/glastopf/modules/handlers/emulators/dork_list/dork_page_generator.py
