### ISSUE TITLE
Glastopf Install on Ubuntu 14.04

### ISSUE THREAD

**Issue by TomHelvey** [mushorg/glastopf#213]
This isn't really an issue, but it might be useful, maybe a doc update?
The install instructions for Ubuntu 12 don't work for 14.04. Here is a modified version that should work for the current AWS Ubuntu AMI.
# !/bin/bashish

<b>Install prerequisites</b>
<i>This is probably specific to Ubuntu 14, I went through the original script one dependency at at time and didn't install anything that was already there.
NOTE: Apache is installed and started with php5, mongodb is also started.</i>
sudo apt-get update
sudo apt-get install python-gevent libevent-dev python2.7-dev build-essential
sudo apt-get install python-sqlalchemy python-lxml
sudo apt-get install python-beautifulsoup mongodb python-pip python-dev
sudo apt-get install git php5 liblapack-dev gfortran libmysqlclient-dev
sudo apt-get install libxml2-dev libxslt-dev
sudo pip install distribute

<b>Kill apache and remove its startup scripts</b>
sudo /etc/init.d/apache2 stop
sudo rm /etc/rc*.d/S91apache2 # I give up, rc-star.d/S-star-apache2

<b>Install and configure the PHP sandbox</b>
cd /opt
sudo git clone https://github.com/glastopf/BFR.git
cd BFR
sudo phpize
sudo ./configure --enable-bfr
sudo make && sudo make install

<b>Open the php.ini file and add bfr.so accordingly to the build output:</b>
 /etc/php5/cli/php.ini
 /etc/php5/apache2/php.ini ??
 zend_extension = /usr/lib/php5/20121212/bfr.so

<b>Downloading hpfeeds as part of the glastopf install blows up so do it manually first</b>
sudo git clone https://github.com/rep/hpfeeds.git
cd hpfeeds
sudo python setup.py install

<b>Install latest stable release from pip:</b>
sudo pip install glastopf

<b>Or install latest development version from the repository:</b>
cd /opt
sudo git clone https://github.com/glastopf/glastopf.git
cd glastopf
sudo python setup.py install

<b>Prepare glastopf environment:</b>
<i>Note: This also starts glastopf, so you have to make sure apache is stopped first
Apache is installed and started when php5 is installed</i>
cd /opt
sudo mkdir myhoneypot
cd myhoneypot
sudo glastopf-runner

A new default glastopf.cfg has been created in myhoneypot, which can be customized as required.

**Comment by glaslos** [comment]
Would you mind submitting your changes as a pull request?

**Comment by akanshgulati** [comment]
Can I install directly with python setup.py install command?

**Comment by sh4t** [comment]
need php5-dev to use phpize btw. just a heads up
