### ISSUE TITLE
Identificator of Glastopf sensor 

### ISSUE THREAD

**Issue by Mato-Z** [mushorg/glastopf#223]
Hello,
I use one MySQL database with default database schema for event logging from all Glastopf sensors. Is possible clearly identify each sensor during SQL querying in some way?
Thank you for reply.

**Comment by glaslos** [comment]
Hey @Mato-Z any suggestion what to use as an id?

**Comment by Mato-Z** [comment]
Hello @glaslos I think, that, it would be "sensorid" item which would add to Glastopf config as use Conpot in this time...

**Comment by nsmfoo** [comment]
I can take a shoot at this one, if there is no objection? As I'm currently messing up the database schema adding sensorid/sensorname to the mix can't make it worse ..

**Comment by katkad** [comment]
go for it ;)

**Comment by Mato-Z** [comment]
@nsmfoo Any progress please? :-)

**Comment by nsmfoo** [comment]
@Mato-Z yes, I have working code ready. Just ended up in github hell. As soon as I can figure out whats wrong I will create a pull request, sorry

**Comment by Mato-Z** [comment]
@nsmfoo Great! I look forward for it :-) Thanks!

**Comment by nsmfoo** [comment]
Thanks to @katkad for solving my git mess =)

**Comment by katkad** [comment]
done by https://github.com/mushorg/glastopf/commit/412b39574f516361aeadea6b6fc694d45ae1da29 and previous commits
