### ISSUE TITLE
adding own website to glastopf

### ISSUE THREAD

**Issue by athariqkanz** [mushorg/glastopf#234]
I'm trying to integrate my own vulnerable website to glastopf. How to change the default template so I can access my own website with glastopf?

**Comment by SilenCtrl** [comment]
I have the same problem. What you did for the issue?
I also want to make my own website,someoen can help me?

**Comment by glaslos** [comment]
Have you had a look at https://github.com/mushorg/snare ? It's the successor of Glastopf.

**Comment by SilenCtrl** [comment]
I try it,but I don't know what snare has to do with glastopf.
![image](https://cloud.githubusercontent.com/assets/18691823/18775553/268d41b6-8195-11e6-919e-0025916f72b1.png)
![image](https://cloud.githubusercontent.com/assets/18691823/18775653/c2169024-8195-11e6-816d-27f10024f45e.png)

**Comment by glaslos** [comment]
Snare is the next version of Glastopf. You don't want to use Glastopf anymore. Snare is much better :)
