### ISSUE TITLE
glastopf pylibinjection installation instruction for raspberry pi

### ISSUE THREAD

**Issue by bunk3r** [mushorg/glastopf#242]
Hi!

There's an error in the installation procedure for pylibinjection:

------- OLD ----------
cd /opt
git clone https://github.com/client9/libinjection.git
git clone https://github.com/glastopf/pylibinjection.git
rm /opt/pylibinjection/src/pylibinjection.c
cd pylibinjection/
python setup.py build

------- NEW ----------
cd /opt
git clone https://github.com/glastopf/pylibinjection.git
rm /opt/pylibinjection/src/pylibinjection.c
cd /opt/pylibinjection/submodules
git clone https://github.com/client9/libinjection.git
cd /opt/pylibinjection/submodules/libinjection
ln -s src c
cd /opt/pylibinjection/
python setup.py build

hope this is helpful to users

**Comment by katkad** [comment]
well, pull request for this would be useful, I think ;)
