### ISSUE TITLE
POST to admin-ajax.php always crashes glastopf

### ISSUE THREAD

**Issue by bunk3r** [mushorg/glastopf#246]
Sometimes my glastopf crashes.
When it happens this is always the last line in the log:

```
requested POST /wp-admin/admin-ajax.php?page=pmxi-admin-settings&action=upload&name=info.php
```

How can I find the details of POST parameters, to debug this specific problem?

**Comment by katkad** [comment]
sqlite3 db/glastopf.db

and there is table events where you can find additional information

for example:
select * from events where request_raw LIKE '%pmxi-admin-settings%';

**Comment by katkad** [comment]
No answer. I am closing this issue.
Reopen if still occures.
