### ISSUE TITLE
MySQL logger' object has no attribute 'conn' glastopf

### ISSUE THREAD

**Issue by CMarvel** [mushorg/glastopf#256]
Using Debian 7 Wheezy.. Getting this in my glastopf log. No other errors... MySQL logger' object has no attribute 'conn' glastopf

**Comment by katkad** [comment]
hello, nothing more ? no Traceback ?

can you copy couple of line before the error ?
and after the error maybe too.

**Comment by katkad** [comment]
No answer. I am closing this issue.
Reopen if still occures.
