### ISSUE TITLE
hpfeeds port 20000 error

### ISSUE THREAD

**Issue by brendan004** [mushorg/glastopf#260]
Hello. I see it's been a LONG time since this was addressed. I noticed that http://map.honeynet.org/ no longer populates data. I've been trying to get Glastopf to work and run in to the same issues as we have seen here:
error: [Errno 111] Connection refused
2016-02-24 17:18:13,537 (pyhpfeeds) FeedException while connecting: Could not connect to broker [hpfriends.honeycloud.net].
2016-02-24 17:18:33,561 (pyhpfeeds) connecting to hpfriends.honeycloud.net:20000
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/hpfeeds.py", line 137, in connect
self.s.connect((addr, self.port))
File "/usr/local/lib/python2.7/dist-packages/gevent/socket.py", line 344, in connect
raise error(err, strerror(err))
error: [Errno 111] Connection refused
2016-02-24 17:18:33,745 (pyhpfeeds) FeedException while connecting: Could not connect to broker [hpfriends.honeycloud.net].

Is this project dead in the water? Glastopf comes with Honeydrive3 so I thought it would run out of the box. It does not. I also followed your installation instructions found here:
https://github.com/mushorg/glastopf/blob/master/docs/source/installation/installation_ubuntu.rst

I have also commented out hpfeeds section in /honeydrive/glastopf-honeypot/glastopf.cfg:
[hpfeed]
#enabled = True
#host = hpfriends.honeycloud.net
#port = 20000
#secret = 3wis3l2u5l7r3cew
channels comma separated

#chan_events = glastopf.events
#chan_files = glastopf.files
#ident = x8yer@hp1

Thoughts? I do not have port 20000 blocked outbound.

**Comment by katkad** [comment]
hello, the issue is hpfeeds is currently down. you can disable hpfeeds by setting it to false.  I hope it will be running soon, but no guarante on that.

[hpfeed]
enabled = False

**Comment by brendan004** [comment]
Thanks katkad! I've uncommented out that line and set it to False. It appears it still runs fine when receiving this error but I guess it's trying to provide data for the mapping project. It will be nice to stop having to weed through these errors in the logs...

**Comment by katkad** [comment]
if you don't want hpfeeds errors, just set hpfeed to false in config file. it should do.
