### ISSUE TITLE
MySQL table error

### ISSUE THREAD

**Issue by alfonsocaponi** [mushorg/glastopf#267]
If you want use MySQL you should modify "**comments = Column(String(65536))**" type in "**glastopf/modules/processing/ip_profile.py**" to avoid "**sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (1074, u"Column length too big for column 'comments' (max = 65535); use BLOB or TEXT instead")**" error during table creation.

I'm using mysql-client-5.7 on a "Ubuntu 16.04 LTS".

**Comment by glaslos** [comment]
See dee5637e3bab3350434ec102de404188778d5dd6
