### ISSUE TITLE
hpfeeds wont shut off

### ISSUE THREAD

**Issue by dirtdiver512** [mushorg/glastopf#269]
All,

I have uncommented and changed to false yet it still shows up in the logs.

```
[hpfeed]
enabled = False
host = hpfriends.honeycloud.net
port = 20000
secret = 3wis3l2u5l7r3cew
# channels comma separated
chan_events = glastopf.events
chan_files = glastopf.files
ident = x8yer@hp1
```

**Comment by glaslos** [comment]
Which version of Glastopf are you using?
Have you looked into using SNARE? https://github.com/mushorg/snare

**Comment by katkad** [comment]
I just tried it, and no problem.

Is your glastopf.cfg in glastopf work directory ? (first line when you start glastopf)
