### ISSUE TITLE
How to make my own web template?

### ISSUE THREAD

**Issue by SilenCtrl** [mushorg/glastopf#276]
I want to make my own web template to collect webshells. But I have no idea how to do. Can someone help me?
I have successfully installed the glastopf:
![image](https://cloud.githubusercontent.com/assets/18691823/18739147/1069619c-80d4-11e6-9eb3-9992ce4f4f2c.png)

**Comment by glaslos** [comment]
In Glastopfs data directory which is created during the initialization you can find a template file called base.html modifying this should give you the desired result.

**Comment by SilenCtrl** [comment]
Can I remove the base.html or I can only modify the base.html?
![image](https://cloud.githubusercontent.com/assets/18691823/18772316/62b08c24-8178-11e6-9271-06df96067cc8.png)
If I can only modify the date between %%?
Sorry,my english is not good.

**Comment by glaslos** [comment]
The other way around. Don't change any of the {% block_name %} ... {% endblock %} elements in the template. You can change all HTML in that file.

**Comment by SilenCtrl** [comment]
I tryed to do that but it's still a problem. It seems like glastopf can only show one page. for example, the page has another url, when clicked the Web page can't jump.
eg base.html:
`<html>
<body>
	<li class="has-dropdown-2"><a href="#">About</a>
		<ul class="subnav-level-2">
			<li><a href="about-1.html">About 1</a></li>
			<li><a href="about-2.html">About 2</a></li>
			<li><a href="about-3.html">About 3</a></li>
		</ul>
	</li>
</body>	
</html>`
about-1.html,about-2.html,about-3.html are under the same directory.When clicked the About 1,it can't jump to about-1.html.

**Comment by SilenCtrl** [comment]
In fact, I just need a page, this page can be used to upload files. But how do I link this page to MHN? MHN will record and I will get the uploaded file when it is found that there is an attacker to upload the file.

**Comment by glaslos** [comment]
Yes, the only page you can serve is Glastopf is the base.html if you want a more complex page, you have to use SNARE. If you want to use MHN, create an issue with them to add SNARE to MHN.

**Comment by glaslos** [comment]
Closing this for now.

**Comment by camaro23** [comment]
Hey glaslos,

How can I make change the text at the very top of the webpage to text I want to display? For example, in Bi3g0's screenshot where the text "curriculum vitae" is.

Thanks
