### ISSUE TITLE
row size too large

### ISSUE THREAD

**Issue by bunk3r** [mushorg/glastopf#281]
Fresh install on raspberry-pi:

> sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1118, 'Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. You have to change some columns to TEXT or BLOBs') [SQL: u'\nCREATE TABLE ip_profiles (\n\tip VARCHAR(15) NOT NULL, \n\tas_number VARCHAR(10), \n\tas_name VARCHAR(120), \n\tcountry_code VARCHAR(10), \n\ttotal_requests INTEGER, \n\ttotal_scans INTEGER, \n\tbgp_prefix VARCHAR(100), \n\trequests_per_scan FLOAT, \n\tavg_scan_duration FLOAT, \n\tscan_time_period FLOAT, \n\tlast_event_time VARCHAR(30), \n\tcomments VARCHAR(65535), \n\tPRIMARY KEY (ip)\n)\n\n']

> mysql  Ver 14.14 Distrib 5.5.47, for debian-linux-gnu (armv7l) using readline 6.3

**Comment by glaslos** [comment]
Hey @bunk3r I recommend using [SNARE ](github.com/mushorg/snare) instead of Glastopf.
