### ISSUE TITLE
make && make install error

### ISSUE THREAD

**Issue by S1yFox** [mushorg/glastopf#282]
when running 
`make &&  make install`
i recieved this error:

/bin/bash /opt/BFR/libtool --mode=compile cc -Werror -Wall -I. -I/opt/BFR -DPHP_ATOM_INC -I/opt/BFR/include -I/opt/BFR/main -I/opt/BFR -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -DHAVE_CONFIG_H  -g -O2   -c /opt/BFR/php_bfr.c -o php_bfr.lo 
libtool: compile:  cc -Werror -Wall -I. -I/opt/BFR -DPHP_ATOM_INC -I/opt/BFR/include -I/opt/BFR/main -I/opt/BFR -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DHAVE_CONFIG_H -g -O2 -c /opt/BFR/php_bfr.c  -fPIC -DPIC -o .libs/php_bfr.o
/opt/BFR/php_bfr.c: In function 'zif_override_function':
/opt/BFR/php_bfr.c:152:2: error: implicit declaration of function 'zend_hash_str_find_ptr' [-Werror=implicit-function-declaration]
  if ((func = zend_hash_str_find_ptr(EG(function_table),
  ^
/opt/BFR/php_bfr.c:152:12: error: assignment makes pointer from integer without a cast [-Werror]
  if ((func = zend_hash_str_find_ptr(EG(function_table),
            ^
/opt/BFR/php_bfr.c:163:2: error: implicit declaration of function 'zend_hash_str_exists' [-Werror=implicit-function-declaration]
  if (zend_hash_str_exists(EG(function_table),
  ^
/opt/BFR/php_bfr.c:166:3: error: implicit declaration of function 'zend_hash_str_del' [-Werror=implicit-function-declaration]
   zend_hash_str_del(EG(function_table),
   ^
/opt/BFR/php_bfr.c:170:2: error: implicit declaration of function 'zend_hash_str_add_new_ptr' [-Werror=implicit-function-declaration]
  if (zend_hash_str_add_new_ptr(EG(function_table),
  ^
/opt/BFR/php_bfr.c:172:19: error: comparison between pointer and integer [-Werror]
         func_dup) == NULL)
                   ^
/opt/BFR/php_bfr.c: In function 'zif_rename_function':
/opt/BFR/php_bfr.c:207:12: error: assignment makes pointer from integer without a cast [-Werror]
  if ((func = zend_hash_str_find_ptr(EG(function_table),
            ^
/opt/BFR/php_bfr.c:227:2: error: implicit declaration of function 'zend_hash_str_add_ptr' [-Werror=implicit-function-declaration]
  if (zend_hash_str_add_ptr(EG(function_table), z_new_fname, new_fname_len, func_dup) == NULL)
  ^
/opt/BFR/php_bfr.c:227:86: error: comparison between pointer and integer [-Werror]
  if (zend_hash_str_add_ptr(EG(function_table), z_new_fname, new_fname_len, func_dup) == NULL)
                                                                                      ^
cc1: all warnings being treated as errors
Makefile:180: recipe for target 'php_bfr.lo' failed
make: *** [php_bfr.lo] Error 1

**Comment by hannyseva** [comment]
I also encountered this. have been looking somewhere else but it still doesn't help :(

**Comment by glaslos** [comment]
Please report BFR related issues in the BFR repository: https://github.com/mushorg/BFR
