### ISSUE TITLE
Glastop does not work with HTTPS traffic

### ISSUE THREAD

**Issue by StevePham88** [mushorg/glastopf#283]
Hi,
I'm using the glastopf listening on port 80/http and 443/https. Http traffics have been handled well but https is not working. Somehow, glastops has not supported to handle https traffic? Any idea for that?
![Uploading image.png…]()
![capture](https://user-images.githubusercontent.com/19483861/34933866-1ce1b594-fa0b-11e7-8be1-10950c8a9bc8.PNG)

**Comment by glaslos** [comment]
Glastopf doesn't support HTTPS. If you want HTTPS with Glastopf, you have to setup a proxy in front of Glastopf that terminates HTTPS.
I'd recommend using SNARE and TANNER instead of Glastopf: https://github.com/mushorg/snare

**Comment by StevePham88** [comment]
Hi,
Snare and tanner requires a few more to setup, i have already played with Glastopf, anyway to continue use Glastopf to capture 443 traffic? I just want to capture the whole 443 traffic content in order to see which is the real malformed URL the user had accessed.

**Comment by glaslos** [comment]
Then you have to use the proxy method.

**Comment by StevePham88** [comment]
Can you provide me more detail please? Thanks

**Comment by StevePham88** [comment]
i found Mitmproxy is able to handle https traffic, how i can config Mitmproxy as a proxy in front of Glastopf?
