### ISSUE TITLE
Segmentation Fault on glastopf-runner

### ISSUE THREAD

**Issue by ertzaaafzal** [mushorg/glastopf#301]
I have installed Glastopf on my RaspberryPi using the instructions given here.

When I issue the `glastopf-runner` command I get the following error:

`2019-10-29 11:27:48,569 (root) Glastopf SSL config broken. Check SSL config section.
2019-10-29 11:27:48,570 (glastopf.glastopf) Initializing Glastopf 3.1.3-dev using "/opt/myhoneypot" as work directory.
Segmentation fault`

I have tried to remove and re-install everything but the issue persists and I cannot seem to find the reason for it. 

Pip freeze output:
`attrs==16.3.0
automationhat==0.1.0
BeautifulSoup==3.2.1
beautifulsoup4==4.5.3
blinker==1.3
blinkt==0.1.2
botocore==1.12.62
buttonshim==0.0.2
Cap1xxx==0.1.3
certifi==2019.9.11
chardet==3.0.4
click==6.6
colorama==0.3.7
constantly==15.1.0
cryptography==1.7.1
cssselect==1.0.3
Cython==0.29.1
docutils==0.14
drumhat==0.1.0
enum34==1.1.6
envirophat==1.0.0
ExplorerHAT==0.4.2
Flask==0.12.1
fourletterphat==0.1.0
gevent==1.2.0
Glastopf==3.1.3.dev0
gpiozero==1.4.1
greenlet==0.4.11
hpfeeds==1.0
html5lib==0.999999999
idna==2.8
incremental==16.10.1
ipaddress==1.0.17
itsdangerous==0.24
Jinja2==2.8
jmespath==0.9.3
keyring==10.1
keyrings.alt==1.3
libtaxii==1.1.112
lxkeymap==0.1
lxml==4.2.5
MarkupSafe==0.23
mcpi==0.1.1
meld3==1.0.2
microdotphat==0.2.1
mote==0.0.4
motephat==0.0.2
MySQL-python==1.2.5
numpy==1.12.1
oauthlib==2.0.1
PAM==0.4.2
pantilthat==0.0.7
phatbeat==0.1.1
pianohat==0.1.0
picamera==1.13
picraft==1.0
piglow==1.2.4
pigpio==1.38
Pillow==4.0.0
pyasn1==0.1.9
pyasn1-modules==0.0.7
pycrypto==2.6.1
pygame==1.9.3
pygobject==3.22.0
pyinotify==0.9.6
PyJWT==1.4.2
pylibinjection==0.2.4
pymongo==3.7.2
pyOpenSSL==16.2.0
pyserial==3.2.1
python-dateutil==2.7.5
python-logstash==0.4.6
pyxdg==0.25
rainbowhat==0.1.0
requests==2.22.0
requests-oauthlib==0.7.0
RPi.GPIO==0.6.5
RTIMULib==7.2.1
scrollphat==0.0.7
scrollphathd==1.2.1
SecretStorage==2.3.1
sense-emu==1.1
sense-hat==2.2.0
service-identity==16.0.0
simplejson==3.10.0
six==1.10.0
skywriter==0.0.7
sn3218==1.2.7
spidev==3.3
SQLAlchemy==1.3.0b1
supervisor==3.3.1
touchphat==0.0.1
Twisted==16.6.0
twython==3.4.0
unicornhathd==0.0.4
urllib3==1.24.2
webencodings==0.5
WebOb==1.8.4
Werkzeug==0.11.15
zope.interface==4.3.2
`

**Comment by glaslos** [comment]
Which version of Python are you using?
Disable SSL or provide certificates.
I highly recommend [SNARE](https://github.com/mushorg/snare) instead of Glastopf.

**Comment by ertzaaafzal** [comment]
Hi @glaslos , I am using Python 2.7

Anyways I debugged the program and the issue occurs when it tries to import `log_taxii` auxiliary reporting module. I wasn't using it and had it already disabled in the conf, so deleted the `log_taxii.py`  file from the modules and everything seems to work fine now. 

I may look into what exactly is causing the segmentation fault when importing this module at a later time and would update here. For now removing the module works as a workaround.

Also, I wasn't aware of SNARE, thank you for pointing it out. I'll definitely look into switching over and it seems much promising.
