### ISSUE TITLE
not work with docker...GPG with invalid signatures...

### ISSUE THREAD

**Issue by tom9un** [mushorg/glastopf#302]
Step 5/13 : RUN apt-get update && apt-get install -y         build-essential         g++         gfortran         git         libevent-dev         liblapack-dev         libmysqlclient-dev         libxml2-dev         libxslt-dev         make         python-beautifulsoup         python-chardet         python-dev         python-gevent         python-lxml         python-openssl         python-pip         python-requests         python-setuptools         python-sqlalchemy         python-mysqldb         cython         python-dateutil         python2.7         python2.7-dev         software-properties-common 	&&     apt-get clean &&     rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
 ---> Running in 3b4e62f74ad9
Ign http://archive.ubuntu.com trusty InRelease
Get:1 http://mirror.deace.id/ubuntu/ trusty-security InRelease [65.9 kB]
Get:2 http://mirror.deace.id/ubuntu/ trusty-backports InRelease [65.9 kB]
Get:3 http://archive.ubuntu.com trusty-updates InRelease [65.9 kB]
Get:4 http://mirror.deace.id/ubuntu/ trusty-updates InRelease [65.9 kB]
Get:5 http://archive.ubuntu.com trusty-security InRelease [65.9 kB]
Hit http://archive.ubuntu.com trusty Release.gpg
Get:6 http://archive.ubuntu.com trusty-updates/main Sources [532 kB]
Get:7 http://archive.ubuntu.com trusty-updates/restricted Sources [6444 B]
Get:8 http://archive.ubuntu.com trusty-updates/universe Sources [288 kB]
Get:9 http://archive.ubuntu.com trusty-updates/main amd64 Packages [1460 kB]
Ign http://mirror.deace.id/ubuntu/ trusty InRelease
Get:10 http://mirror.deace.id/ubuntu/ trusty-security/main amd64 Packages [1032 kB]
Get:11 http://mirror.deace.id/ubuntu/ trusty-security/universe amd64 Packages [18.1 kB]
Get:12 http://mirror.deace.id/ubuntu/ trusty-backports/main amd64 Packages [377 kB]
Get:13 http://mirror.deace.id/ubuntu/ trusty-backports/universe amd64 Packages [4730 B]
Get:14 http://mirror.deace.id/ubuntu/ trusty-updates/main amd64 Packages [14.7 kB]
Get:15 http://mirror.deace.id/ubuntu/ trusty-updates/universe amd64 Packages [40 B]
Get:16 http://mirror.deace.id/ubuntu/ trusty Release.gpg [52.5 kB]
Get:17 http://mirror.deace.id/ubuntu/ trusty-security/multiverse amd64 Packages [1392 B]
Get:18 http://mirror.deace.id/ubuntu/ trusty-backports/multiverse amd64 Packages [1460 kB]
Get:19 http://archive.ubuntu.com trusty-updates/restricted amd64 Packages [21.4 kB]
Get:20 http://archive.ubuntu.com trusty-updates/universe amd64 Packages [671 kB]
Hit http://archive.ubuntu.com trusty Release
Get:21 http://archive.ubuntu.com trusty-security/main Sources [220 kB]
Get:22 http://archive.ubuntu.com trusty-security/restricted Sources [5050 B]
Get:23 http://archive.ubuntu.com trusty-security/universe Sources [126 kB]
Get:24 http://archive.ubuntu.com trusty-security/main amd64 Packages [1032 kB]
Get:25 http://archive.ubuntu.com trusty-security/restricted amd64 Packages [18.1 kB]
Get:26 http://archive.ubuntu.com trusty-security/universe amd64 Packages [377 kB]
Get:27 http://archive.ubuntu.com trusty/main Sources [1335 kB]
Get:28 http://mirror.deace.id/ubuntu/ trusty-updates/multiverse amd64 Packages [21.4 kB]
Get:29 http://mirror.biznetgio.com/ubuntu/ trusty Release [58.5 kB]
Ign mirror://mirrors.ubuntu.com trusty Release
E: GPG error: mirror://mirrors.ubuntu.com trusty Release: The following signatures were invalid: NODATA 1 NODATA 2
The command '/bin/sh -c apt-get update && apt-get install -y         build-essential         g++         gfortran         git         libevent-dev         liblapack-dev         libmysqlclient-dev         libxml2-dev         libxslt-dev         make         python-beautifulsoup         python-chardet         python-dev         python-gevent         python-lxml         python-openssl         python-pip         python-requests         python-setuptools         python-sqlalchemy         python-mysqldb         cython         python-dateutil         python2.7         python2.7-dev         software-properties-common 	&&     apt-get clean &&     rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*' returned a non-zero code: 100

**Comment by glaslos** [comment]
https://stackoverflow.com/questions/38002543/apt-get-update-returned-a-non-zero-code-100
