### ISSUE TITLE
Does this glastopf provide for sql injection attack detection?

### ISSUE THREAD

**Issue by shoonlaiyee** [mushorg/glastopf#303]
where can I view the logs for SQL injection attack? The glastopf website didn't show any changes even the attacker logged in to the website? Is not this too obvious for attacker?

**Comment by glaslos** [comment]
Hey @shoonlaiyee , please use https://github.com/mushorg/snare

**Comment by shoonlaiyee** [comment]
Does the Snare provide for SQL detection?

**Comment by glaslos** [comment]
yes
