### ISSUE TITLE
Filtering Non-Invasive Behaviors in Glastopf Reports to MHN

### ISSUE THREAD

**Issue by DreamRuthenium** [mushorg/glastopf#309]
I have successfully deployed Glastopf in conjunction with MHN (Modern Honey Network), a platform designed to centralize alerts using hpfeeds. However, I've noticed an issue where even non-invasive behaviors, such as spider requests and benign requests (e.g., for style.css), are being reported to MHN. This results in a large number of false alerts.

Is there a way to configure Glastopf to only report truly invasive behaviors? I am looking for a solution to reduce the volume of these non-critical alerts.

Thank you for your assistance.

**Comment by glaslos** [comment]
Hey, did you consider using [SNARE](https://github.com/mushorg/snare)?
You could modify the [rules](https://github.com/mushorg/glastopf/blob/master/glastopf/requests.xml) into a module which does not report.

**Comment by DreamRuthenium** [comment]
Thanks, I'll try it
