### ISSUE TITLE
Support for Google/Bing web master tools page verification

### ISSUE THREAD

**Issue by glaslos** [mushorg/glastopf#66]
Both tools are very essential in monitoring and advertising your honeypot. Easy support for verifying your domain with those tools should be available.

**Comment by akanshgulati** [comment]
I have tried to add all the extra lines of code to respective files. But still no sign of meta tag in index.html. Moreover, is there any way to update glastopf file to newer version resolving all issues?

**Comment by adarshdinesh** [comment]
@akanshgulati : Make sure that you did the changes according to this : https://github.com/glastopf/glastopf/commit/283f0e4bb01738816e1da48ee4a666b463283eb9. Or just do a <pre>git pull</pre> and make your update your local repo.

**Comment by akanshgulati** [comment]
@adarshdinesh Thanks for the reply. I tried with the pull. It worked perfectly. But still it`s not working.
Sharing the glastopf.cfg.dist file info

Removed comments from both urls and added the meta values.
https://www.google.com/webmasters/
google_meta =8658E02866DDCB24113fake
http://www.bing.com/toolbox/webmaster
bing_meta =8658E02866DDCB24113BFfake

**Comment by adarshdinesh** [comment]
@glaslos: Ooops.. We shouldn't have added those commented URLs.
@akanshgulati: Keep the URL commented don't edit it. Just add the meta there. like this
[surface]
#https://www.google.com/webmasters/
google_meta = 8658E02866DDCB24113
#http://www.bing.com/toolbox/webmaster
bing_meta = 8658E02866DDCB24113B
Hope this will help

**Comment by akanshgulati** [comment]
@adarshdinesh it`s still not working. I executed "git pull" in the /opt/glastopf/ directory.

**Comment by adarshdinesh** [comment]
Is it showing some errors or something while starting ? Check nosetests and make sure that 'Test google/bing meta' is working.

**Comment by akanshgulati** [comment]
@adarshdinesh  can I have your email id or skype username ?

**Comment by adarshdinesh** [comment]
It's better you close this and open a new issue. This is a completed Task.

**Comment by adarshdinesh** [comment]
@akanshgulati : You upload your config file here and screenshots of the problem. I will try if I can do something. Its better if you could create a new issue.

**Comment by akanshgulati** [comment]
@adarshdinesh Yeah, I will create a new issue. You can close this thread.Thanks
